spring:
  datasource:
    url: 'jdbc:h2:mem:omnipede'
    driverClassName: 'org.h2.Driver'
    username: 'omnipede'
    password: '1234'
  h2:
    console:
      enabled: true
      path: /test_db
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show-sql: true